### ISSUE TITLE
Enable Checker's concurrent semantics 

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#276] opened 2020-05-12 15:40 UTC
TBH to spot cases like that, I'd turn on Checker's _concurrent semantics_ for the entire project (or at least for `frontendActions`): https://checkerframework.org/manual/#faq-concurrency

_Originally posted by @PawelLipski in https://github.com/VirtusLab/git-machete-intellij-plugin/pull/245_

In scope of this task:
- add `-AconcurrentSemantics` to checker's `extraJavacArgs` 
- resolve possible code issues

**Comment by PawelLipski** [comment] 2020-05-12 17:56
I inspected the errors raised by Checker when concurrent semantics is turned on, basically all of them are caused by associated limitations on flow-sensitive type refinement (https://checkerframework.org/manual/#type-refinement) rather than by actual concurrency-related issues. Not worth introducing, closing the issue.

**Closed by PawelLipski** 2020-05-12 17:56 UTC
Labels: code, tech debt
