### ISSUE TITLE
New, empty branch considered as merged after parent pull

### ISSUE THREAD

**Issue by micpiotrowski** [VirtusLab/git-machete-intellij-plugin#603] opened 2020-10-01 20:01 UTC
## Bug description
Assume, we have a develop with unpulled changes from remote. Then we slide-in new branch as a child of develop. Next, we pull the develop. Now edge between develop and newly created branch is gray, but should be red.

**Comment by mkondratek** [comment] 2020-10-02 09:57
I would not consider this one as a bug; this is rather an expected behavior...

you create a branch B from A
you pull A, A becomes A', B still points to A (which is supposed to be behind A')
branches pointing commits behind other branches are considered to be merged 

that's all

However, in the first moment, it seems to be a nice feature to automatically "rebase" 0-commit branches (cause this is what it is about actually). 
On the other hand, this is not something that a user would expect to happen after the pull (possibly we should hide it behind some git config).

**Comment by micpiotrowski** [comment] 2020-10-02 10:13
I'd still considering this as a bug - branch B (from your example) was not merged into A but edge indicates it was.

> branches pointing commits behind other branches are considered to be merged

and probably this is a problem (bug). Probably we should take into consideration not only current commit graph but maybe also branches reflog or something else.

**Comment by PawelLipski** [comment] 2020-10-02 10:28
I agree with @micpiotrowski; this should be relatively easy fix (since @mkondratek: rebasing 0-commit branches is indeed implemented by `git rebase` as fast-forwarding)

**Comment by PawelLipski** [comment] 2020-10-04 21:29
Currently, the algorithm for selecting between green or gray edge is (P = parent branch, C = child branch):

* if P is descendant or equal to C:
  * if P is descendant of C: *gray edge*
  * if P is equal to C:
    * if filtered reflog (reflog without branch creation and resets) of C is empty: C has just been created, so *green edge*
    * else: there has been some non-trivial activity on C, hence C is merged, so *gray edge*

**Comment by PawelLipski** [comment] 2020-10-04 21:38
The first case (`if P is descendant of C: gray edge`) could just leave the Rebase action available (alongside Slide Out), even without marking the edge as red :thinking:

**Comment by PawelLipski** [comment] 2020-10-13 13:11
Possibly adding a new `SyncToParentStatus` will be necessary to handle that case... although I can't say at the moment, maybe it can be done in other way

**Comment by PawelLipski** [comment] 2020-10-13 13:12
> leave the Rebase action available

I'd actually only make the rebase action available from context menu, but **not** suggest it from the toolbar (since slide-out is most commonly needed in that case; rebase isn't the default choice)

**Comment by PawelLipski** [comment] 2020-10-23 16:28
Closed by #622.

**Closed by PawelLipski** 2020-10-23 16:28 UTC
Labels: backend, bug
