### ISSUE TITLE
Branch name is absent from slide-out dialog

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#736] opened 2021-04-28 16:49 UTC
...which may lead to someone misclicking and removing the wrong branch.

**Comment by DcortezMeleth** [comment] 2022-02-17 10:11
I like the idea but I'm not sure whether adding branch name to current slide-out dialog is enough.

Why is that? As far as I understand correctly, right now this dialogs opens only when:
* you are trying to slide out branch other then the one you are currently on 
* you don't have appropriate git config property set (you didn't click remember action button)
So we will still have use cases where you can have missclicks, because you may not see the dialog at all.

So I can see 2 (or 3 depending how you look at it) solutions here.
1. We only add branch name in the dialog with deletion suggestion. Least amount of work but I'm not sure what is the percentile of covered use cases.
2. We add additional confirmation window where we specifically ask user whether he is sure he want to delete branch `xyz`.
2.1. For use case where we are going to display deletion suggestion dialog we may merge it.
2.2. For use case where we are going to display deletion suggestion we will display 2 dialogs, one after the other.

Personally I would prefer solution 2.2. even if that introduces additional work for us and effort for user.
@PawelLipski What is your opinion on that?

**Comment by PawelLipski** [comment] 2022-02-17 18:35
> So we will still have use cases where you can have missclicks, because you may not see the dialog at all.

Hmmm for clarity: what specific scenario of a _not seeing a dialog at all_ do you mean here?

Note that when sliding out the currently checked out branch, this branch is **never** deleted, regardless of git config 🤔

**Comment by PawelLipski** [comment] 2022-02-19 16:57
> but for true machete will delete branch without presenting any dialog to the user.
Yes! but pls note that it's up to the user to set this git config... either directly via `git config machete.slideOut.deleteLocalBranch true`, or by clicking an option in the IntelliJ dialog (which also sets the very same git config under the hood.

So... _volenti non fit iniuria_ ;) I've got this config set to `true` on certain repos &mdash; esp. the ones where the PRs are usually very trivial in terms of code changes, like a repo driving [ArgoCD](https://argo-cd.readthedocs.io/en/stable/).

**Comment by DcortezMeleth** [comment] 2022-02-22 09:58
Ok. If that's enough I can probably take this one.
Do you already have some proposition on how/where do you want to display this name?
Or should I look at this dialog and propose sth?

**Comment by PawelLipski** [comment] 2022-02-22 13:14
Feel free to propose your own solution... any place where it's **hard to miss** would make it!

**Comment by DcortezMeleth** [comment] 2022-02-25 10:14
I have created PR. You can take a look at it. 

But what I have noticed while resolving this issue is that `SlideOutCurrentBranchAction` seems to be called very often even if you only have machete tab opened and don't click anything in there. Is that correct/expected behaviour?

Below you can see logs to understand frequency I talk about. You see them as a warning because when I set up debug there it's always slow, even when I click continue right away. But here I would say that it's actually benefiting us, as you can see those number more easily.
```
2022-02-25 11:08:38,472 [ 306469]   WARN - #c.i.o.a.i.ActionUpdater - 4774 ms to call on EDT SlideOutCurrentBranchAction#update (com.virtuslab.gitmachete.frontend.actions.toolbar.SlideOutCurrentBranchAction) - speed it up and/or implement UpdateInBackground.
2022-02-25 11:08:40,129 [ 308126]   WARN - #c.i.o.a.i.ActionUpdater - 1143 ms to call on EDT SlideOutCurrentBranchAction#update (com.virtuslab.gitmachete.frontend.actions.toolbar.SlideOutCurrentBranchAction) - speed it up and/or implement UpdateInBackground.
2022-02-25 11:08:44,538 [ 312535]   WARN - #c.i.o.a.i.ActionUpdater - 1797 ms to call on EDT SlideOutCurrentBranchAction#update (com.virtuslab.gitmachete.frontend.actions.toolbar.SlideOutCurrentBranchAction) - speed it up and/or implement UpdateInBackground.
2022-02-25 11:08:46,138 [ 314135]   WARN - #c.i.o.a.i.ActionUpdater - 1093 ms to call on EDT SlideOutCurrentBranchAction#update (com.virtuslab.gitmachete.frontend.actions.toolbar.SlideOutCurrentBranchAction) - speed it up and/or implement UpdateInBackground.
2022-02-25 11:08:49,568 [ 317565]   WARN - #c.i.o.a.i.ActionUpdater - 1142 ms to call on EDT SlideOutCurrentBranchAction#update (com.virtuslab.gitmachete.frontend.actions.toolbar.SlideOutCurrentBranchAction) - speed it up and/or implement UpdateInBackground.
2022-02-25 11:08:50,145 [ 318142]   WARN - #c.i.o.a.i.ActionUpdater - 547 ms to call on EDT SlideOutCurrentBranchAction#update (com.virtuslab.gitmachete.frontend.actions.toolbar.SlideOutCurrentBranchAction) - speed it up and/or implement UpdateInBackground.
2022-02-25 11:08:53,879 [ 321876]   WARN - #c.i.o.a.i.ActionUpdater - 931 ms to call on EDT SlideOutCurrentBranchAction#update (com.virtuslab.gitmachete.frontend.actions.toolbar.SlideOutCurrentBranchAction) - speed it up and/or implement UpdateInBackground.
2022-02-25 11:08:55,027 [ 323024]   WARN - #c.i.o.a.i.ActionUpdater - 641 ms to call on EDT SlideOutCurrentBranchAction#update (com.virtuslab.gitmachete.frontend.actions.toolbar.SlideOutCurrentBranchAction) - speed it up and/or implement UpdateInBackground.
2022-02-25 11:08:59,132 [ 327129]   WARN - #c.i.o.a.i.ActionUpdater - 1255 ms to call on EDT SlideOutCurrentBranchAction#update (com.virtuslab.gitmachete.frontend.actions.toolbar.SlideOutCurrentBranchAction) - speed it up and/or implement UpdateInBackground.
2022-02-25 11:08:59,791 [ 327788]   WARN - #c.i.o.a.i.ActionUpdater - 625 ms to call on EDT SlideOutCurrentBranchAction#update (com.virtuslab.gitmachete.frontend.actions.toolbar.SlideOutCurrentBranchAction) - speed it up and/or implement UpdateInBackground.
```

**Comment by DcortezMeleth** [comment] 2022-02-25 10:19
Also one more thought. Would it be beneficial to add some information on this dialog, that `Remember my choice` is not some Intellij default behaviour, but rather our own addition, which under the hood adds git config entry like this: `machete.slideOut.deleteLocalBranch = true`? 
Why am I asking that? Actually I had set it once for test purposes and was searching Intellij docs on how to forget. Only by reading code I have realised that I'm looking for a solution in a wrong place.

**Comment by PawelLipski** [comment] 2022-02-28 18:48
> But what I have noticed while resolving this issue is that SlideOutCurrentBranchAction seems to be called very often even if you only have machete tab opened and don't click anything in there. Is that correct/expected behaviour?

Yes! `#update` method is called for registered actions periodically on UI thread just for IntelliJ to re-evaluate whether they should be visible/enabled.

> 4774 ms to call

But these long execution times are very unsettling... does IntelliJ actually freeze for that 4 seconds when this call happens?

**Comment by PawelLipski** [comment] 2022-02-28 18:48
> Also one more thought. Would it be beneficial to add some information on this dialog, that Remember my choice is not some Intellij default behaviour, but rather our own addition, which under the hood adds git config entry like this: machete.slideOut.deleteLocalBranch = true?

Lemme follow-up on the PR itself...

**Comment by DcortezMeleth** [comment] 2022-03-03 14:11
This long times are caused by Intellij debug breakpoint being set there. It's the only reason the call times are so high.

**Comment by PawelLipski** [comment] 2022-03-03 16:52
Oh! okay 😌 I was afraid some heavyweight action happens there

Yes, the frequent UI-thread calls to `update` are well expected

**Closed** 2022-03-28 14:17 UTC
Labels: good first issue, ux, frontend-actions
