### ISSUE TITLE
Reset to Remote action is not automatically followed by status refresh

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#551] opened 2020-08-27 16:49 UTC
Would be nice to check with other actions as well, maybe more of them would require an explicit `refreshStatus` call

**Comment by mkondratek** [comment] 2020-08-28 17:41
Isn't it? Works to me. Both current and non-current branches checked. The refresh happens instantly.

I assume that there may be some delays since the refresh is being triggered by the `GitRepository.GIT_REPO_CHANGE` topic.

**Comment by PawelLipski** [comment] 2020-08-31 13:20
@mkondratek possibly a heisenbug... yeah, I'm aware that it should be refreshed automatically, but it only ever happens for me when doing the reset, not for any other action :/ @micpiotrowski have you ever observed such a lack of refresh yourself? :thinking:

**Comment by mkondratek** [comment] 2020-09-01 19:26
@PawelLipski 
1. Does the issue occur to you for both current and non-current branch?
2. Does it appear on fast forward or pull too? (that would blame `FetchBackgroundable`)

**Comment by micpiotrowski** [comment] 2020-09-02 09:30
For me every action (including current and non-current) is working correctly (refresh graph as they should)

**Comment by mkondratek** [comment] 2020-09-02 14:13
@PawelLipski's unsuccessfully reattempted to reproduce the issue. closing

**Comment by PawelLipski** [comment] 2020-09-09 20:13
Whoops, still occurring quite often as of v0.7.1. Noticed the two characteristics:
* only happens when resetting the **current branch** (so it's related to `git reset`, not `git fetch`),
* usually does NOT happen when recently preceded by another reset (although that's pretty fuzzy).

**Comment by PawelLipski** [comment] 2020-09-09 20:15
It would be good to investigate the implementation of reset to remote for the current branch, whether&when the git repo change topic is notified. If we find nothing, we can still explicitly call `refreshStatus` from reset action as a workaround.

**Comment by mkondratek** [comment] 2020-09-10 12:00
@PawelLipski have you disabled (checked do not show it again) the info dialog?

**Comment by PawelLipski** [comment] 2020-09-10 12:27
@mkondratek yes, quite a long time ago already

**Comment by PawelLipski** [comment] 2020-09-18 13:10
Hmm apart from `BaseResetBranchToRemoteAction#doResetCurrentBranchToRemoteWithKeepdoResetCurrentBranchToRemoteWithKeep`, the only other place in our codebase where `Git.getInstance().runCommand(handler)` is invoked is `GitCommandUpdatingCurrentBranchBackgroundable#run`.

The difference I can see is that the former is missing `gitRepository.update();`... but maybe it's a matter of sth different.

Also, shoudn't we call `VfsUtil.markDirtyAndRefresh(...)` from Reset to Remote action as well?

**Comment by micpiotrowski** [comment] 2020-09-18 15:23
I can confirm this happen only after `do not show it again` checkbox was checked and practically only for current branch

**Comment by mkondratek** [comment] 2020-09-18 15:58
> I can confirm this happen only after `do not show it again` checkbox was checked and practically only for current branch

Actually, I managed to reproduce it (accidentally ofc) with `do not show it again` dialog

**Comment by micpiotrowski** [comment] 2020-09-18 16:09
The cause was missing repository and VFS update after current branch reset.
Probably this reset dialog fotce (in some strange way) refreshing of repository and VFS.

**Closed** 2020-09-21 11:38 UTC
Labels: bug, frontend-actions
