### ISSUE TITLE
Entry to machete file added even when slide-in failed

### ISSUE THREAD

**Issue by micpiotrowski** [VirtusLab/git-machete-intellij-plugin#464] opened 2020-07-30 21:17 UTC
In case when slide in failure (e.g. submodule misconfiguration) new branch entry is added to `machete` file anyway

**Comment by mkondratek** [comment] 2020-07-31 10:41
@micpiotrowski please add the specific steps to reproduce this one

**Comment by micpiotrowski** [comment] 2020-07-31 11:08
1. create git repository and subrepository in it
2. corrupt submodule settings (e.g. edit patch to submodule in `main-repo/.git/modules/<submodule-name>/config` in `worktree` key
3. try to to slide in new branch in that submodule repo

As effect branch will not been created (creation failure) but branch entry will be added to `machete` file

This is one of examples why branch creation may failed (in this case it is missconfiguration)

**Comment by PawelLipski** [comment] 2020-07-31 12:41
> corrupt submodule settings (e.g. edit path to submodule ...)

Hmm to be fair very little can be guaranteed (also by `git` itself) in case someone corrupts vital settings like this one...

**Comment by PawelLipski** [comment] 2020-07-31 12:43
I think this one is at most `minor` (if it's an issue at all) unless it's also likely to affect users in more frequent corner cases

**Comment by micpiotrowski** [comment] 2020-07-31 13:08
> Hmm to be fair very little can be guaranteed (also by `git` itself) in case someone corrupts vital settings like this one...

Yes, I agree but the same think can happen if by any other reason branch will not been created.
But ok, it's not so important as now.

**Comment by mkondratek** [comment] 2020-08-03 06:52
@micpiotrowski but do we know **any other reason** that might lead to this issue?

After a quick look at the present approach, I can say that there is no way to handle branch creation failures. 
Ofc we could get deeper and use `GitBranchWorker` (where the handling **seems** to be possible) directly.
We lose the reused dialog then.

**Comment by micpiotrowski** [comment] 2020-08-03 07:04
> @micpiotrowski but do we know **any other reason** that might lead to this issue?

Actually, no.

> After a quick look at the present approach, I can say that there is no way to handle branch creation failures.
> Ofc we could get deeper and use GitBranchWorker (where the handling seems to be possible) directly.
> We lose the reused dialog then.

So leave as is. It seems to be really not so important that I think at the beginning.

**Comment by PawelLipski** [comment] 2020-09-30 14:07
Whoops, actually this seems to also happen when the checkout is declined by the user (due to possible file conflicts)... branch is still getting slid in. Which I think merits removing the `minor` label :/

**Comment by vzmerr** [comment] 2022-09-23 09:20
I have a little bit of problem in reproducing the issue.

**Comment by PawelLipski** [comment] 2022-09-23 09:37
Quite likely the issue no longer exists, might've been fixed over the last two years without us noticing ;) Closing then

**Closed by PawelLipski** 2022-09-23 09:37 UTC
Labels: bug

**Comment by vzmerr** [comment] 2022-09-23 10:27
new issue: the entry does not get deleted from the machete file, upon the deletion of the branch.

**Comment by PawelLipski** [comment] 2022-09-23 11:05
> upon the deletion of the branch

You mean when branch is deleted e.g. via `git branch -d ...`, **outside** of git-machete right? that's expected in general!
