### ISSUE TITLE
[investigation] Refreshing Status takes a significant amount of time in the case of extensive repositories

### ISSUE THREAD

**Issue by mkondratek** [VirtusLab/git-machete-intellij-plugin#583] opened 2020-09-15 12:03 UTC
# Scenario 

## Having:

[repo](https://github.com/JetBrains/intellij-community) like this:

![image](https://user-images.githubusercontent.com/19799111/93206387-9d370480-f759-11ea-9401-bff2836941bd.png)

## When:

I slid out a branch

## Then:

Refresh took about **20 s**

---

Ofc this still seems to be livable.

## In the scope of this task:
- determine the specific source of time elongation
- find out a solution

--- 

My thinking is that it may be related to the number of commits processed. 
If so, the issue is inevitable (as we need to process them all to determine sync to parent status). 

We could monitor the time and suggest (by notification or a "don't show it again" dialog) not to use git machete with such a distance b/w branches.

**Comment by PawelLipski** [comment] 2023-02-20 18:56
Probably was caused by #1394! closing

**Comment by PawelLipski** [comment] 2023-02-20 18:56
(fixed on #1395)

**Closed** 2023-02-20 18:56 UTC
Labels: research needed, ux, performance
