### ISSUE TITLE
Check if the plugin can be suggested by IntelliJ for projects containing .git/machete file

### ISSUE THREAD

**Issue by PawelLipski** [VirtusLab/git-machete-intellij-plugin#277] opened 2020-05-13 09:37 UTC
https://plugins.jetbrains.com/legal/approval-guidelines -> `Approval Criteria for Features Implemented by Plugins`

https://github.com/JetBrains/intellij-plugin-verifier/tree/master/intellij-feature-extractor

**Comment by mkondratek** [comment] 2020-06-01 19:02
To verify once changes from #272 will be released

**Comment by mkondratek** [comment] 2020-07-03 08:41
The result from `com.jetbrains.intellij.feature.extractor.CliMainKt#main`:
`{"extensionPoint":"FILE_TYPE","featureNames":["machete"]}`

You can try it yourself if you want. My args are: 
`/home/mkondratek/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/201.7846.76.plugins/git-machete-intellij-plugin /home/mkondratek/.local/share/JetBrains/Toolbox/apps/IDEA-C/ch-0/201.7846.76`

**Comment by mkondratek** [comment] 2020-07-03 08:44
I tried to run IDE without the plugin and open a machete file. 
Sadly no plugin suggestion appeared. :confused: 

@PawelLipski, @micpiotrowski can you try it?

**Comment by mkondratek** [comment] 2020-07-03 09:20
On the other hand, I think that this (the plugin suggestion) is not very useful in our case.
The plugin suggestion should appear only once the machete file is opened within IDE. 
It is rather a rare situation since the machete file belongs to the hidden directory (`.git`).

**Comment by PawelLipski** [comment] 2020-07-03 10:34
> The plugin suggestion should appear only once the machete file is opened within IDE.
Whoops okay, given this limitation it's rather unlikely that the plugin suggestion will ever be useful.
It'd only make sense if IDEA could recognize the .git/machete file existing in the repository even if it's ignored/not opened in the IDE

**Comment by PawelLipski** [comment] 2020-07-03 10:37
> Sadly no plugin suggestion appeared

No suggestion for me, either :/ but given the limited usability, let's close the issue

**Comment by mkondratek** [comment] 2020-07-03 19:08
whoops

![image](https://user-images.githubusercontent.com/19799111/86493211-e558a480-bd70-11ea-8e34-60d583bdbaf9.png)

It seems that we just need to wait a bit longer. 
I think we can try it again then.

**Comment by mkondratek** [comment] 2020-07-13 12:49
Note: no longer `on approval`

**Comment by mkondratek** [comment] 2020-07-13 12:58
**CONFIRMED** it works!

![image](https://user-images.githubusercontent.com/19799111/87307089-4b83bb00-c519-11ea-86dc-71d150a62c3e.png)

**Closed** 2020-07-13 12:59 UTC
Labels: distribution, minor
